# Generated by Django 4.1.6 on 2023-02-10 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=60)),
                ('cp', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=60)),
                ('auteur', models.CharField(max_length=60)),
                ('jaquette', models.CharField(max_length=60)),
                ('editeur', models.CharField(max_length=60)),
                ('collection', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=60)),
                ('bibliotheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.biliotheque')),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
