# Generated by Django 4.1.6 on 2023-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_livre_dispo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='dispo',
            field=models.BooleanField(default=True),
        ),
    ]
