# Generated by Django 4.1.6 on 2023-02-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pret_rendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='dateend',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
