# Generated by Django 4.1.6 on 2023-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pret_dateend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='dateend',
            field=models.DateTimeField(),
        ),
    ]
