# Generated by Django 4.1.6 on 2023-02-12 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_pret_dateend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pret',
            name='rendu',
        ),
        migrations.AddField(
            model_name='pret',
            name='daterendu',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
